// Element catalog — all landscape elements available in the game
// REBALANCED: wider cost spread (1-5), sharper specializations, lower base scores
// Design: cheap elements are enablers, expensive elements are synergy anchors

export interface ElementDefinition {
  type: string;
  name: string;
  category: string;
  description: string;
  funFacts?: string[];
  spriteKey: string;
  width: number;
  height: number;
  cost: number;
  baseScores: { biodiversity: number; sustainability: number; aesthetics: number; ecosystemHealth: number };
  properties: {
    isNative: boolean;
    providesShade: boolean;
    attractsPollinators: boolean;
    waterAbsorption: number;
    carbonSequestration: number;
    wildlifeValue: number;
    shadeRequirement: string;
    waterRequirement: string;
  };
}

export const ELEMENT_CATALOG: ElementDefinition[] = [
  // === TREES (3-4 coins — anchor pieces, strong synergy magnets) ===
  {
    type: 'oak_tree',
    name: 'Oak Tree',
    category: 'trees',
    description: 'Long-lived native oak reaching 80–100 ft. Acorns feed deer, turkeys, and songbirds while the canopy hosts hundreds of moth and butterfly species.',
    funFacts: [
      'A single oak can produce 70,000 acorns per year',
      'Supports 500+ species of caterpillars',
      'Can live over 200 years',
    ],
    spriteKey: 'oak_tree',
    width: 64,
    height: 64,
    cost: 4,
    baseScores: { biodiversity: 6, sustainability: 5, aesthetics: 5, ecosystemHealth: 7 },
    properties: {
      isNative: true,
      providesShade: true,
      attractsPollinators: false,
      waterAbsorption: 7,
      carbonSequestration: 9,
      wildlifeValue: 9,
      shadeRequirement: 'full_sun',
      waterRequirement: 'medium',
    },
  },
  {
    type: 'maple_tree',
    name: 'Maple Tree',
    category: 'trees',
    description: 'Native maple with brilliant red and orange fall foliage. Feeds birds, squirrels, and pollinators with early-spring blooms.',
    funFacts: [
      'Red maples are one of the first trees to bloom in spring',
      'Seeds spin like tiny helicopters when they fall',
      'Fall leaves turn red, orange, and yellow all on one tree',
    ],
    spriteKey: 'maple_tree',
    width: 64,
    height: 64,
    cost: 4,
    baseScores: { biodiversity: 4, sustainability: 4, aesthetics: 8, ecosystemHealth: 5 },
    properties: {
      isNative: true,
      providesShade: true,
      attractsPollinators: false,
      waterAbsorption: 6,
      carbonSequestration: 8,
      wildlifeValue: 7,
      shadeRequirement: 'full_sun',
      waterRequirement: 'medium',
    },
  },
  {
    type: 'pine_tree',
    name: 'Pine Tree',
    category: 'trees',
    description: 'Tall evergreen native to the SE US, providing year-round shelter and seeds for birds and squirrels. Fast-growing with dense needles that support wildlife across all seasons.',
    funFacts: [
      'Loblolly pines can grow 2 ft per year',
      'Pine needles make natural mulch that enriches soil',
      'Bald eagles prefer tall pines for nesting',
    ],
    spriteKey: 'pine_tree',
    width: 48,
    height: 64,
    cost: 3,
    baseScores: { biodiversity: 3, sustainability: 6, aesthetics: 4, ecosystemHealth: 5 },
    properties: {
      isNative: true,
      providesShade: true,
      attractsPollinators: false,
      waterAbsorption: 4,
      carbonSequestration: 7,
      wildlifeValue: 6,
      shadeRequirement: 'full_sun',
      waterRequirement: 'low',
    },
  },
  {
    type: 'fruit_tree',
    name: 'Fruit Tree',
    category: 'trees',
    description: 'Spring blossoms attract bees and butterflies, including Eastern Tiger Swallowtails. Fruit feeds small mammals and birds through summer and fall.',
    funFacts: [
      'A single apple tree can produce 800 lbs of fruit per year',
      'Fruit trees need pollinators — no bees, no fruit!',
      'Fallen fruit feeds foxes, deer, and box turtles',
    ],
    spriteKey: 'fruit_tree',
    width: 48,
    height: 56,
    cost: 3,
    baseScores: { biodiversity: 5, sustainability: 5, aesthetics: 5, ecosystemHealth: 4 },
    properties: {
      isNative: false,
      providesShade: true,
      attractsPollinators: true,
      waterAbsorption: 5,
      carbonSequestration: 5,
      wildlifeValue: 8,
      shadeRequirement: 'full_sun',
      waterRequirement: 'medium',
    },
  },

  // === SHRUBS (2 coins — versatile mid-range workhorses) ===
  {
    type: 'native_shrub',
    name: 'Native Shrub',
    category: 'shrubs',
    description: 'Dense native shrub providing critical wildlife cover. Bright berries feed 48+ bird species through winter.',
    funFacts: [
      'Winterberry holly berries last all winter for hungry birds',
      'Dense branches hide nests from predators',
      'Native shrubs support 10x more caterpillars than non-native ones',
    ],
    spriteKey: 'native_shrub',
    width: 40,
    height: 36,
    cost: 2,
    baseScores: { biodiversity: 4, sustainability: 3, aesthetics: 2, ecosystemHealth: 4 },
    properties: {
      isNative: true,
      providesShade: false,
      attractsPollinators: true,
      waterAbsorption: 4,
      carbonSequestration: 3,
      wildlifeValue: 7,
      shadeRequirement: 'any',
      waterRequirement: 'low',
    },
  },
  {
    type: 'berry_bush',
    name: 'Berry Bush',
    category: 'shrubs',
    description: 'Produces summer berries eaten by songbirds, bears, and small mammals. Spring blooms attract native bees and butterflies.',
    funFacts: [
      'Blueberries are one of the only fruits native to North America',
      'Birds can strip a berry bush clean in a single day',
      'Berry bushes turn brilliant red in fall',
    ],
    spriteKey: 'berry_bush',
    width: 36,
    height: 32,
    cost: 2,
    baseScores: { biodiversity: 5, sustainability: 3, aesthetics: 3, ecosystemHealth: 3 },
    properties: {
      isNative: true,
      providesShade: false,
      attractsPollinators: true,
      waterAbsorption: 3,
      carbonSequestration: 2,
      wildlifeValue: 8,
      shadeRequirement: 'partial_shade',
      waterRequirement: 'medium',
    },
  },
  {
    type: 'hedge_row',
    name: 'Hedge Row',
    category: 'shrubs',
    description: 'Dense native shrubs form living corridors for nesting birds and pollinators. Evergreen hedgerows block wind, shelter wildlife, and connect fragmented habitats.',
    funFacts: [
      'Hedgerows can be wildlife highways connecting isolated habitats',
      'A single hedgerow can shelter 60+ bird species',
      'Hedges reduce wind speed by up to 50%',
    ],
    spriteKey: 'hedge_row',
    width: 64,
    height: 28,
    cost: 2,
    baseScores: { biodiversity: 3, sustainability: 2, aesthetics: 3, ecosystemHealth: 5 },
    properties: {
      isNative: true,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 3,
      carbonSequestration: 3,
      wildlifeValue: 6,
      shadeRequirement: 'any',
      waterRequirement: 'low',
    },
  },

  // === FLOWERS (1-2 coins — wildflowers are premium, shade fern is cheap enabler) ===
  {
    type: 'wildflower_patch',
    name: 'Wildflower Patch',
    category: 'flowers',
    description: 'Native wildflower mix of coneflowers and black-eyed Susans. Attracts bees, butterflies, and songbirds across three seasons of bloom.',
    funFacts: [
      'Black-eyed Susans bloom for up to 3 months straight',
      'Coneflower seeds are a favorite winter food for goldfinches',
      'Wildflower meadows support 3x more pollinators than lawns',
    ],
    spriteKey: 'wildflower_patch',
    width: 40,
    height: 32,
    cost: 2,
    baseScores: { biodiversity: 5, sustainability: 3, aesthetics: 6, ecosystemHealth: 4 },
    properties: {
      isNative: true,
      providesShade: false,
      attractsPollinators: true,
      waterAbsorption: 3,
      carbonSequestration: 2,
      wildlifeValue: 7,
      shadeRequirement: 'full_sun',
      waterRequirement: 'low',
    },
  },
  {
    type: 'sunflower_cluster',
    name: 'Sunflower Cluster',
    category: 'flowers',
    description: 'Towering up to 10 ft tall with bold yellow blooms that attract bees and butterflies. Leave seed heads standing to feed birds through winter.',
    funFacts: [
      'Sunflower heads track the sun across the sky (heliotropism)',
      'A single head can contain up to 2,000 seeds',
      'Sunflower roots can pull toxins out of contaminated soil',
    ],
    spriteKey: 'sunflower_cluster',
    width: 36,
    height: 44,
    cost: 2,
    baseScores: { biodiversity: 3, sustainability: 2, aesthetics: 6, ecosystemHealth: 3 },
    properties: {
      isNative: true,
      providesShade: false,
      attractsPollinators: true,
      waterAbsorption: 2,
      carbonSequestration: 1,
      wildlifeValue: 6,
      shadeRequirement: 'full_sun',
      waterRequirement: 'medium',
    },
  },
  {
    type: 'shade_fern',
    name: 'Shade Fern',
    category: 'flowers',
    description: 'Evergreen understory fern that holds moisture and prevents erosion on shaded slopes. Provides year-round ground cover and nesting material for songbirds.',
    funFacts: [
      'Christmas ferns stay green all winter under the snow',
      'Ferns are ancient — they existed before dinosaurs',
      'Birds line their nests with soft fern fronds',
    ],
    spriteKey: 'shade_fern',
    width: 32,
    height: 28,
    cost: 1,
    baseScores: { biodiversity: 2, sustainability: 3, aesthetics: 4, ecosystemHealth: 3 },
    properties: {
      isNative: true,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 5,
      carbonSequestration: 1,
      wildlifeValue: 3,
      shadeRequirement: 'full_shade',
      waterRequirement: 'high',
    },
  },

  // === GROUND COVER (1 coin — cheap fillers, great synergy enablers) ===
  {
    type: 'native_grass',
    name: 'Native Grass',
    category: 'ground_cover',
    description: 'Deep-rooted native grasses that prevent erosion and build soil health. Seeds feed songbirds while dense clumps shelter wildlife year-round.',
    funFacts: [
      'Native grass roots can grow 10–15 ft deep',
      'Switchgrass was the dominant plant of the American prairie',
      'Grasslands store more carbon underground than forests do',
    ],
    spriteKey: 'native_grass',
    width: 48,
    height: 24,
    cost: 1,
    baseScores: { biodiversity: 2, sustainability: 5, aesthetics: 2, ecosystemHealth: 3 },
    properties: {
      isNative: true,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 6,
      carbonSequestration: 3,
      wildlifeValue: 4,
      shadeRequirement: 'full_sun',
      waterRequirement: 'low',
    },
  },
  {
    type: 'moss_patch',
    name: 'Moss Patch',
    category: 'ground_cover',
    description: 'Shade-loving moss that absorbs many times its weight in water, preventing erosion. A low-maintenance ground cover that shelters insects and retains moisture year-round.',
    funFacts: [
      'Moss can absorb up to 20x its dry weight in water',
      'Moss has no roots — it absorbs water through its leaves',
      'Some mosses can survive being completely dried out for years',
    ],
    spriteKey: 'moss_patch',
    width: 40,
    height: 20,
    cost: 1,
    baseScores: { biodiversity: 2, sustainability: 4, aesthetics: 3, ecosystemHealth: 3 },
    properties: {
      isNative: true,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 8,
      carbonSequestration: 1,
      wildlifeValue: 2,
      shadeRequirement: 'full_shade',
      waterRequirement: 'high',
    },
  },
  {
    type: 'clover_ground',
    name: 'Clover Ground Cover',
    category: 'ground_cover',
    description: 'Fixes nitrogen in soil and spreads as a living mat. Attracts bees and butterflies while enriching depleted ground.',
    funFacts: [
      'Clover makes its own fertilizer by pulling nitrogen from the air',
      'A four-leaf clover is a 1 in 5,000 mutation',
      'Honeybees love clover — it is their top nectar source',
    ],
    spriteKey: 'clover_ground',
    width: 44,
    height: 22,
    cost: 1,
    baseScores: { biodiversity: 3, sustainability: 5, aesthetics: 2, ecosystemHealth: 4 },
    properties: {
      isNative: true,
      providesShade: false,
      attractsPollinators: true,
      waterAbsorption: 5,
      carbonSequestration: 2,
      wildlifeValue: 5,
      shadeRequirement: 'any',
      waterRequirement: 'low',
    },
  },

  // === WATER FEATURES (1-5 coins — wide range, pond is premium cornerstone) ===
  {
    type: 'rain_garden',
    name: 'Rain Garden',
    category: 'water_features',
    description: 'A planted depression that captures and filters stormwater runoff.',
    funFacts: [
      'Rain gardens can absorb 30% more water than a lawn',
      'They filter pollutants like oil and fertilizer from runoff',
      'A rain garden recharges groundwater naturally',
    ],
    spriteKey: 'rain_garden',
    width: 56,
    height: 48,
    cost: 4,
    baseScores: { biodiversity: 4, sustainability: 8, aesthetics: 5, ecosystemHealth: 6 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: true,
      waterAbsorption: 10,
      carbonSequestration: 3,
      wildlifeValue: 6,
      shadeRequirement: 'full_sun',
      waterRequirement: 'high',
    },
  },
  {
    type: 'small_pond',
    name: 'Small Pond',
    category: 'water_features',
    description: 'A small pond supporting amphibians, insects, and birds.',
    funFacts: [
      'Even a small pond can support frogs, dragonflies, and newts',
      'Ponds are the most biodiverse habitat per square foot',
      'Dragonfly larvae live in ponds for up to 5 years before flying',
    ],
    spriteKey: 'small_pond',
    width: 56,
    height: 44,
    cost: 5,
    baseScores: { biodiversity: 7, sustainability: 4, aesthetics: 6, ecosystemHealth: 7 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 10,
      carbonSequestration: 1,
      wildlifeValue: 10,
      shadeRequirement: 'any',
      waterRequirement: 'high',
    },
  },
  {
    type: 'birdbath',
    name: 'Bird Bath',
    category: 'water_features',
    description: 'A simple water source attracting birds to the garden.',
    funFacts: [
      'Birds need water for drinking and bathing to keep feathers clean',
      'Moving water attracts more bird species than still water',
      'Birdbaths can attract species that never visit feeders',
    ],
    spriteKey: 'birdbath',
    width: 28,
    height: 32,
    cost: 1,
    baseScores: { biodiversity: 3, sustainability: 1, aesthetics: 4, ecosystemHealth: 2 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 1,
      carbonSequestration: 0,
      wildlifeValue: 7,
      shadeRequirement: 'any',
      waterRequirement: 'high',
    },
  },

  // === STRUCTURES (1-3 coins — utility pieces, shine through synergies) ===
  {
    type: 'birdhouse',
    name: 'Birdhouse',
    category: 'structures',
    description: 'Nesting box providing shelter for cavity-nesting birds.',
    funFacts: [
      'Bluebirds, wrens, and chickadees all use nest boxes',
      'The entrance hole size determines which birds move in',
      'A birdhouse should face away from prevailing winds',
    ],
    spriteKey: 'birdhouse',
    width: 24,
    height: 36,
    cost: 1,
    baseScores: { biodiversity: 3, sustainability: 1, aesthetics: 3, ecosystemHealth: 2 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 0,
      carbonSequestration: 0,
      wildlifeValue: 8,
      shadeRequirement: 'any',
      waterRequirement: 'low',
    },
  },
  {
    type: 'insect_hotel',
    name: 'Insect Hotel',
    category: 'structures',
    description: 'A shelter for beneficial insects like solitary bees and ladybugs.',
    funFacts: [
      'Solitary bees pollinate 90% of wild plants worldwide',
      'Ladybugs eat up to 5,000 aphids in a lifetime',
      'Mason bees are 100x more efficient pollinators than honeybees',
    ],
    spriteKey: 'insect_hotel',
    width: 28,
    height: 32,
    cost: 3,
    baseScores: { biodiversity: 6, sustainability: 2, aesthetics: 3, ecosystemHealth: 5 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: true,
      waterAbsorption: 0,
      carbonSequestration: 0,
      wildlifeValue: 9,
      shadeRequirement: 'any',
      waterRequirement: 'low',
    },
  },
  {
    type: 'compost_bin',
    name: 'Compost Bin',
    category: 'structures',
    description: 'Recycles organic waste into rich soil nutrients.',
    funFacts: [
      'Compost can be ready in as little as 3 months',
      'Worms in a compost bin can eat half their weight daily',
      'Composting reduces landfill methane emissions',
    ],
    spriteKey: 'compost_bin',
    width: 28,
    height: 28,
    cost: 2,
    baseScores: { biodiversity: 1, sustainability: 7, aesthetics: 1, ecosystemHealth: 5 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 2,
      carbonSequestration: 4,
      wildlifeValue: 4,
      shadeRequirement: 'any',
      waterRequirement: 'low',
    },
  },

  {
    type: 'bench',
    name: 'Park Bench',
    category: 'structures',
    description: 'A wooden bench inviting visitors to sit and watch birds. Encourages people to slow down, observe wildlife, and connect with the sanctuary.',
    funFacts: [
      'Sitting quietly for 10 min lets wildlife return and forage nearby',
      'Birdwatchers discover more species by sitting still than walking',
      'Benches near water or feeders see the most bird activity',
    ],
    spriteKey: 'bench',
    width: 40,
    height: 28,
    cost: 2,
    baseScores: { biodiversity: 1, sustainability: 2, aesthetics: 7, ecosystemHealth: 1 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 0,
      carbonSequestration: 0,
      wildlifeValue: 2,
      shadeRequirement: 'any',
      waterRequirement: 'low',
    },
  },

  // === WILDLIFE HABITAT (2 coins — ecosystem builders) ===
  {
    type: 'log_pile',
    name: 'Log Pile',
    category: 'wildlife_habitat',
    description: 'Decomposing logs providing habitat for insects and small animals.',
    funFacts: [
      'A rotting log can house beetles, salamanders, and fungi',
      'Decomposing wood returns nutrients to the soil for decades',
      'Fireflies lay their eggs in moist, decaying wood',
    ],
    spriteKey: 'log_pile',
    width: 44,
    height: 28,
    cost: 2,
    baseScores: { biodiversity: 4, sustainability: 3, aesthetics: 2, ecosystemHealth: 5 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 3,
      carbonSequestration: 2,
      wildlifeValue: 8,
      shadeRequirement: 'partial_shade',
      waterRequirement: 'medium',
    },
  },
  {
    type: 'rock_garden',
    name: 'Rock Garden',
    category: 'wildlife_habitat',
    description: 'Rocks providing basking spots for reptiles and shelter for insects.',
    funFacts: [
      'Lizards and snakes bask on warm rocks to regulate body temperature',
      'Gaps between rocks create micro-habitats for ground beetles',
      'Rock gardens need zero watering — great for dry areas',
    ],
    spriteKey: 'rock_garden',
    width: 48,
    height: 32,
    cost: 2,
    baseScores: { biodiversity: 3, sustainability: 4, aesthetics: 5, ecosystemHealth: 3 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 1,
      carbonSequestration: 0,
      wildlifeValue: 5,
      shadeRequirement: 'full_sun',
      waterRequirement: 'low',
    },
  },

  // === INVASIVE (1 coin — learning traps, strong negative effects) ===
  {
    type: 'invasive_vine',
    name: 'Invasive Vine',
    category: 'invasive',
    description: '⚠️ Aggressive vine that smothers native plants. Hurts biodiversity!',
    funFacts: [
      'Kudzu vine can grow up to 1 ft per day in summer',
      'Invasive vines block sunlight and kill trees by smothering them',
      'English ivy damages buildings and trees with clinging roots',
    ],
    spriteKey: 'invasive_vine',
    width: 36,
    height: 36,
    cost: 1,
    baseScores: { biodiversity: -6, sustainability: -4, aesthetics: 2, ecosystemHealth: -7 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 4,
      carbonSequestration: 2,
      wildlifeValue: -3,
      shadeRequirement: 'any',
      waterRequirement: 'low',
    },
  },
  {
    type: 'invasive_grass',
    name: 'Invasive Grass',
    category: 'invasive',
    description: '⚠️ Non-native grass that crowds out native species.',
    funFacts: [
      'Bermuda grass spreads by runners, seeds, and underground stems',
      'Invasive grasses fuel hotter, more frequent wildfires',
      'Non-native grasses provide almost no food for native insects',
    ],
    spriteKey: 'invasive_grass',
    width: 48,
    height: 24,
    cost: 1,
    baseScores: { biodiversity: -5, sustainability: -3, aesthetics: 1, ecosystemHealth: -5 },
    properties: {
      isNative: false,
      providesShade: false,
      attractsPollinators: false,
      waterAbsorption: 3,
      carbonSequestration: 1,
      wildlifeValue: -2,
      shadeRequirement: 'full_sun',
      waterRequirement: 'low',
    },
  },
];

export const ELEMENT_CATEGORIES: { key: string; label: string; color: string }[] = [
  { key: 'trees', label: 'Trees', color: '#2d5a27' },
  { key: 'shrubs', label: 'Shrubs', color: '#4a7c3f' },
  { key: 'flowers', label: 'Flowers', color: '#c94c8e' },
  { key: 'ground_cover', label: 'Ground Cover', color: '#6b8f3c' },
  { key: 'water_features', label: 'Water', color: '#3b82c4' },
  { key: 'structures', label: 'Structures', color: '#8b6914' },
  { key: 'wildlife_habitat', label: 'Habitat', color: '#7a5230' },
  { key: 'invasive', label: 'Invasive ⚠️', color: '#c0392b' },
];

export function getElementDef(type: string): ElementDefinition | undefined {
  return ELEMENT_CATALOG.find((e) => e.type === type);
}
