// Scoring rules: interaction matrix + ecosystem patterns + bonus systems
// REBALANCED: stronger synergies, more interactions, nonlinear diversity, diminishing returns

import type { InteractionRule, EcosystemPattern } from '@/server/src/types/models';

// Diminishing returns: each duplicate element type scores less
// 1st copy: 100%, 2nd: 70%, 3rd: 40%, 4th+: 25%
export const DIMINISHING_RETURNS = [1.0, 0.7, 0.4, 0.25];

// Pairwise interaction rules — elements within radius trigger synergy or conflict
// REBALANCED: values boosted ~60%, many new interactions added
export const INTERACTION_RULES: InteractionRule[] = [
  // === TREE SYNERGIES ===
  {
    elementA: 'oak_tree',
    elementB: 'shade_fern',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'ecosystemHealth',
    value: 8,
    description: 'Fern thrives in oak shade',
  },
  {
    elementA: 'oak_tree',
    elementB: 'moss_patch',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'ecosystemHealth',
    value: 7,
    description: 'Moss benefits from tree shade and moisture',
  },
  {
    elementA: 'oak_tree',
    elementB: 'birdhouse',
    radius: 60,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 9,
    description: 'Birdhouse in oak attracts cavity nesters',
  },
  {
    elementA: 'oak_tree',
    elementB: 'berry_bush',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 6,
    description: 'Berries and acorns provide year-round food',
  },
  {
    elementA: 'fruit_tree',
    elementB: 'wildflower_patch',
    radius: 100,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 8,
    description: 'Pollinators visit both flowers and fruit trees',
  },
  {
    elementA: 'fruit_tree',
    elementB: 'insect_hotel',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 10,
    description: 'Solitary bees pollinate fruit trees',
  },
  {
    elementA: 'fruit_tree',
    elementB: 'berry_bush',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'sustainability',
    value: 7,
    description: 'Food forest layering with trees and shrubs',
  },
  {
    elementA: 'fruit_tree',
    elementB: 'compost_bin',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'sustainability',
    value: 8,
    description: 'Compost feeds fruit tree nutrients',
  },
  {
    elementA: 'pine_tree',
    elementB: 'log_pile',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'ecosystemHealth',
    value: 7,
    description: 'Pine needles and logs create woodland habitat',
  },
  {
    elementA: 'pine_tree',
    elementB: 'moss_patch',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'ecosystemHealth',
    value: 6,
    description: 'Moss thrives on pine forest floor',
  },
  {
    elementA: 'pine_tree',
    elementB: 'rock_garden',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'aesthetics',
    value: 5,
    description: 'Alpine garden effect with pines and rocks',
  },
  {
    elementA: 'maple_tree',
    elementB: 'native_shrub',
    radius: 100,
    effect: 'synergy',
    scoreCategory: 'aesthetics',
    value: 7,
    description: 'Layered canopy creates visual depth',
  },
  {
    elementA: 'maple_tree',
    elementB: 'shade_fern',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'aesthetics',
    value: 6,
    description: 'Ferns under autumn maples create a stunning scene',
  },

  // === WATER SYNERGIES ===
  {
    elementA: 'rain_garden',
    elementB: 'native_grass',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'sustainability',
    value: 9,
    description: 'Grass filters water flowing into rain garden',
  },
  {
    elementA: 'rain_garden',
    elementB: 'clover_ground',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'sustainability',
    value: 8,
    description: 'Clover enriches soil around rain garden',
  },
  {
    elementA: 'rain_garden',
    elementB: 'shade_fern',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'ecosystemHealth',
    value: 6,
    description: 'Ferns thrive in rain garden moisture',
  },
  {
    elementA: 'small_pond',
    elementB: 'native_shrub',
    radius: 100,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 10,
    description: 'Shrubs near water attract diverse wildlife',
  },
  {
    elementA: 'small_pond',
    elementB: 'shade_fern',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'aesthetics',
    value: 8,
    description: 'Ferns by the pond create a natural look',
  },
  {
    elementA: 'small_pond',
    elementB: 'log_pile',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 8,
    description: 'Log pile near water supports amphibians',
  },
  {
    elementA: 'small_pond',
    elementB: 'wildflower_patch',
    radius: 100,
    effect: 'synergy',
    scoreCategory: 'aesthetics',
    value: 7,
    description: 'Flowers reflected in the pond create a scenic view',
  },
  {
    elementA: 'small_pond',
    elementB: 'birdbath',
    radius: 100,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 5,
    description: 'Multiple water sources create a bird oasis',
  },
  {
    elementA: 'birdbath',
    elementB: 'wildflower_patch',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 6,
    description: 'Birds visit bath and then forage nearby flowers',
  },
  {
    elementA: 'birdbath',
    elementB: 'birdhouse',
    radius: 100,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 8,
    description: 'Water and shelter together attract more birds',
  },
  {
    elementA: 'birdbath',
    elementB: 'berry_bush',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 6,
    description: 'Birds flock to berries and water together',
  },

  // === POLLINATOR SYNERGIES ===
  {
    elementA: 'wildflower_patch',
    elementB: 'insect_hotel',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 11,
    description: 'Insect hotel residents pollinate nearby flowers',
  },
  {
    elementA: 'wildflower_patch',
    elementB: 'sunflower_cluster',
    radius: 100,
    effect: 'synergy',
    scoreCategory: 'aesthetics',
    value: 7,
    description: 'Diverse flower display creates vibrant garden',
  },
  {
    elementA: 'sunflower_cluster',
    elementB: 'berry_bush',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 7,
    description: 'Sequential food sources support pollinators',
  },
  {
    elementA: 'sunflower_cluster',
    elementB: 'insect_hotel',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 6,
    description: 'Sunflower nectar feeds hotel residents',
  },
  {
    elementA: 'clover_ground',
    elementB: 'insect_hotel',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'ecosystemHealth',
    value: 8,
    description: 'Clover provides forage for hotel-nesting bees',
  },
  {
    elementA: 'native_shrub',
    elementB: 'wildflower_patch',
    radius: 100,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 5,
    description: 'Shrub border protects delicate wildflowers',
  },

  // === SUSTAINABILITY SYNERGIES ===
  {
    elementA: 'compost_bin',
    elementB: 'native_grass',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'sustainability',
    value: 8,
    description: 'Compost enriches grass growth',
  },
  {
    elementA: 'compost_bin',
    elementB: 'wildflower_patch',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'sustainability',
    value: 7,
    description: 'Compost supports flower growth',
  },
  {
    elementA: 'compost_bin',
    elementB: 'clover_ground',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'sustainability',
    value: 7,
    description: 'Clover nitrogen-fixing boosts compost quality',
  },
  {
    elementA: 'rock_garden',
    elementB: 'native_grass',
    radius: 60,
    effect: 'synergy',
    scoreCategory: 'aesthetics',
    value: 6,
    description: 'Rock and grass create natural landscaping',
  },
  {
    elementA: 'rock_garden',
    elementB: 'moss_patch',
    radius: 60,
    effect: 'synergy',
    scoreCategory: 'aesthetics',
    value: 5,
    description: 'Moss-covered rocks create a zen garden',
  },
  {
    elementA: 'rock_garden',
    elementB: 'shade_fern',
    radius: 60,
    effect: 'synergy',
    scoreCategory: 'aesthetics',
    value: 5,
    description: 'Ferns among rocks create a natural grotto',
  },
  {
    elementA: 'hedge_row',
    elementB: 'birdhouse',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 7,
    description: 'Hedge provides shelter near nesting site',
  },
  {
    elementA: 'hedge_row',
    elementB: 'native_shrub',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'ecosystemHealth',
    value: 5,
    description: 'Connected hedges and shrubs form wildlife corridors',
  },
  {
    elementA: 'hedge_row',
    elementB: 'log_pile',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'ecosystemHealth',
    value: 6,
    description: 'Log pile in hedge creates perfect shelter',
  },
  {
    elementA: 'log_pile',
    elementB: 'insect_hotel',
    radius: 60,
    effect: 'synergy',
    scoreCategory: 'biodiversity',
    value: 7,
    description: 'Double shelter attracts diverse invertebrates',
  },
  {
    elementA: 'log_pile',
    elementB: 'moss_patch',
    radius: 60,
    effect: 'synergy',
    scoreCategory: 'ecosystemHealth',
    value: 5,
    description: 'Moss-covered logs create rich microhabitat',
  },
  {
    elementA: 'clover_ground',
    elementB: 'fruit_tree',
    radius: 80,
    effect: 'synergy',
    scoreCategory: 'sustainability',
    value: 6,
    description: 'Clover fixes nitrogen for fruit tree roots',
  },

  // === CONFLICTS (negative interactions) ===
  // Invasive vine conflicts (boosted)
  {
    elementA: 'invasive_vine',
    elementB: 'native_shrub',
    radius: 100,
    effect: 'conflict',
    scoreCategory: 'biodiversity',
    value: -10,
    description: 'Invasive vine smothers native shrub!',
  },
  {
    elementA: 'invasive_vine',
    elementB: 'wildflower_patch',
    radius: 100,
    effect: 'conflict',
    scoreCategory: 'biodiversity',
    value: -9,
    description: 'Invasive vine overtakes wildflowers!',
  },
  {
    elementA: 'invasive_vine',
    elementB: 'oak_tree',
    radius: 80,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -8,
    description: 'Vine strangles young oak tree!',
  },
  {
    elementA: 'invasive_vine',
    elementB: 'fruit_tree',
    radius: 80,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -7,
    description: 'Vine suffocates fruit tree branches!',
  },
  {
    elementA: 'invasive_vine',
    elementB: 'maple_tree',
    radius: 80,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -6,
    description: 'Vine weighs down maple branches!',
  },
  {
    elementA: 'invasive_vine',
    elementB: 'hedge_row',
    radius: 100,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -6,
    description: 'Vine overtakes hedge formation!',
  },

  // Invasive grass conflicts (boosted)
  {
    elementA: 'invasive_grass',
    elementB: 'native_grass',
    radius: 100,
    effect: 'conflict',
    scoreCategory: 'biodiversity',
    value: -8,
    description: 'Invasive grass outcompetes native species!',
  },
  {
    elementA: 'invasive_grass',
    elementB: 'wildflower_patch',
    radius: 100,
    effect: 'conflict',
    scoreCategory: 'biodiversity',
    value: -7,
    description: 'Invasive grass crowds out wildflowers!',
  },
  {
    elementA: 'invasive_grass',
    elementB: 'clover_ground',
    radius: 80,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -7,
    description: 'Invasive grass displaces beneficial clover!',
  },
  {
    elementA: 'invasive_grass',
    elementB: 'moss_patch',
    radius: 80,
    effect: 'conflict',
    scoreCategory: 'biodiversity',
    value: -5,
    description: 'Invasive grass smothers delicate moss!',
  },
  {
    elementA: 'invasive_grass',
    elementB: 'shade_fern',
    radius: 80,
    effect: 'conflict',
    scoreCategory: 'biodiversity',
    value: -5,
    description: 'Invasive grass crowds out ferns!',
  },

  // === SHADE CONFLICTS (boosted) ===
  {
    elementA: 'oak_tree',
    elementB: 'sunflower_cluster',
    radius: 60,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -5,
    description: 'Sunflowers struggle in oak tree shade',
  },
  {
    elementA: 'pine_tree',
    elementB: 'wildflower_patch',
    radius: 60,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -5,
    description: 'Pine acidic soil and shade harm wildflowers',
  },
  {
    elementA: 'pine_tree',
    elementB: 'native_grass',
    radius: 60,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -4,
    description: 'Pine needles acidify soil, harming grass',
  },
  {
    elementA: 'pine_tree',
    elementB: 'sunflower_cluster',
    radius: 60,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -4,
    description: 'Dense pine shade blocks sun-loving sunflowers',
  },
  {
    elementA: 'maple_tree',
    elementB: 'sunflower_cluster',
    radius: 60,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -3,
    description: 'Maple shade reduces sunflower growth',
  },

  // === CROWDING CONFLICTS (boosted + new) ===
  {
    elementA: 'oak_tree',
    elementB: 'oak_tree',
    radius: 50,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -6,
    description: 'Trees planted too close compete for resources',
  },
  {
    elementA: 'pine_tree',
    elementB: 'pine_tree',
    radius: 50,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -4,
    description: 'Dense pines create sterile monoculture',
  },
  {
    elementA: 'fruit_tree',
    elementB: 'fruit_tree',
    radius: 60,
    effect: 'conflict',
    scoreCategory: 'ecosystemHealth',
    value: -3,
    description: 'Fruit trees compete for pollinators when too close',
  },
  {
    elementA: 'rain_garden',
    elementB: 'rain_garden',
    radius: 80,
    effect: 'conflict',
    scoreCategory: 'sustainability',
    value: -5,
    description: 'Rain gardens too close oversaturate the area',
  },

  // === POLLUTION CONFLICT ===
  {
    elementA: 'small_pond',
    elementB: 'compost_bin',
    radius: 80,
    effect: 'conflict',
    scoreCategory: 'sustainability',
    value: -5,
    description: 'Compost runoff pollutes pond water!',
  },
];

// Ecosystem patterns — bonus for specific combinations
// REBALANCED: bonuses boosted ~50%, 4 new patterns added
export const ECOSYSTEM_PATTERNS: EcosystemPattern[] = [
  {
    name: 'Pollinator Garden',
    description: 'A cluster of pollinator-friendly plants creates a buzzing paradise!',
    requiredElements: [
      { type: 'wildflower_patch', minCount: 1 },
      { type: 'sunflower_cluster', minCount: 1 },
      { type: 'insect_hotel', minCount: 1 },
    ],
    maxRadius: 150,
    bonusPoints: 30,
    category: 'biodiversity',
  },
  {
    name: 'Rain Garden Ecosystem',
    description: 'A water-smart garden that captures runoff and supports wetland plants.',
    requiredElements: [
      { type: 'rain_garden', minCount: 1 },
      { type: 'native_grass', minCount: 1 },
      { type: 'shade_fern', minCount: 1 },
    ],
    maxRadius: 120,
    bonusPoints: 35,
    category: 'sustainability',
  },
  {
    name: 'Wildlife Corridor',
    description: 'Connected native plants form a highway for local wildlife.',
    requiredElements: [
      { type: 'hedge_row', minCount: 2 },
      { type: 'native_shrub', minCount: 1 },
      { type: 'log_pile', minCount: 1 },
    ],
    maxRadius: 200,
    bonusPoints: 40,
    category: 'ecosystemHealth',
  },
  {
    name: 'Bird Sanctuary',
    description: 'Everything a bird needs: food, water, shelter, and nesting.',
    requiredElements: [
      { type: 'birdhouse', minCount: 1 },
      { type: 'birdbath', minCount: 1 },
      { type: 'berry_bush', minCount: 1 },
    ],
    maxRadius: 150,
    bonusPoints: 32,
    category: 'biodiversity',
  },
  {
    name: 'Woodland Edge',
    description: 'A natural forest edge with trees, understory, and ground cover.',
    requiredElements: [
      { type: 'oak_tree', minCount: 1 },
      { type: 'native_shrub', minCount: 1 },
      { type: 'moss_patch', minCount: 1 },
    ],
    maxRadius: 130,
    bonusPoints: 28,
    category: 'ecosystemHealth',
  },
  {
    name: 'Sustainability Hub',
    description: 'A green recycling center with composting and water management.',
    requiredElements: [
      { type: 'compost_bin', minCount: 1 },
      { type: 'rain_garden', minCount: 1 },
      { type: 'clover_ground', minCount: 1 },
    ],
    maxRadius: 150,
    bonusPoints: 32,
    category: 'sustainability',
  },
  {
    name: 'Native Meadow',
    description: 'A restored meadow of native grasses and wildflowers.',
    requiredElements: [
      { type: 'native_grass', minCount: 2 },
      { type: 'wildflower_patch', minCount: 2 },
    ],
    maxRadius: 180,
    bonusPoints: 25,
    category: 'aesthetics',
  },
  {
    name: 'Orchard Grove',
    description: 'A productive fruit grove with pollinators and soil health.',
    requiredElements: [
      { type: 'fruit_tree', minCount: 2 },
      { type: 'clover_ground', minCount: 1 },
      { type: 'insect_hotel', minCount: 1 },
    ],
    maxRadius: 160,
    bonusPoints: 30,
    category: 'sustainability',
  },
  // === NEW PATTERNS ===
  {
    name: 'Zen Garden',
    description: 'A peaceful Japanese-inspired garden of stone, moss, fern, and pine.',
    requiredElements: [
      { type: 'rock_garden', minCount: 1 },
      { type: 'moss_patch', minCount: 1 },
      { type: 'shade_fern', minCount: 1 },
      { type: 'pine_tree', minCount: 1 },
    ],
    maxRadius: 140,
    bonusPoints: 28,
    category: 'aesthetics',
  },
  {
    name: 'Food Forest',
    description: 'A layered forest garden producing food at every level.',
    requiredElements: [
      { type: 'fruit_tree', minCount: 1 },
      { type: 'berry_bush', minCount: 1 },
      { type: 'compost_bin', minCount: 1 },
      { type: 'clover_ground', minCount: 1 },
    ],
    maxRadius: 160,
    bonusPoints: 32,
    category: 'sustainability',
  },
  {
    name: 'Wetland Haven',
    description: 'A thriving wetland ecosystem teeming with life.',
    requiredElements: [
      { type: 'small_pond', minCount: 1 },
      { type: 'rain_garden', minCount: 1 },
      { type: 'native_grass', minCount: 1 },
      { type: 'log_pile', minCount: 1 },
    ],
    maxRadius: 180,
    bonusPoints: 35,
    category: 'biodiversity',
  },
  {
    name: 'Cottage Garden',
    description: 'A charming traditional flower garden with a natural border.',
    requiredElements: [
      { type: 'wildflower_patch', minCount: 1 },
      { type: 'sunflower_cluster', minCount: 1 },
      { type: 'birdbath', minCount: 1 },
      { type: 'hedge_row', minCount: 1 },
    ],
    maxRadius: 160,
    bonusPoints: 26,
    category: 'aesthetics',
  },
];

// Cross-zone bonus config (boosted for more collaborative play)
export const CROSS_ZONE_BONUS = {
  borderDistance: 30, // pixels from zone border
  bonusPerElement: 3,
  maxBonus: 30,
};

// Diversity bonus config — nonlinear scaling rewards using many categories
// Index = number of distinct element categories used, value = total bonus
export const DIVERSITY_BONUS = {
  thresholds: [0, 0, 4, 10, 18, 28, 40, 55, 55],
};
